# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c284a2df8df8e1a86b35c33472743ba9fd872c0e01c0a327aabfa06ed1ff99a7479441b1c52674f609641e35c639e46a1c6e7fc361adb6b5e31280ed98e29827

test:
  secret_key_base: 2856ee384043937058c913a97fdf76c0839df8c1c00de6e3444f31b039fdebbb6f938ee88958757430c8263306aabd0ab80f8ce0dadb679428400ec740aad697

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
